'use strict';
const CFG={id:'AI101-ME',version:'1.0',pass:70,weights:{modules:.7,final:.3},instructor:'[Instructor name]',institution:'[Institution]'};
const MODS=DATA.modules, ALLQ=MODS.flatMap(m=>m.questions), QB=new Map(ALLQ.map(q=>[q.id,q])), TERMS=MODS.flatMap(m=>m.terms.map((t,i)=>({...t,id:m.id+'t'+i,module:m.id}))), TM=new Map(TERMS.map(t=>[t.id,t]));
const LESSONS=new Set(MODS.flatMap(m=>m.lessons.map(l=>l.id))), MODIDS=new Set(MODS.map(m=>m.id)), KEY='ai101-me-progress-v1';
const obj=x=>x!==null&&typeof x==='object'&&!Array.isArray(x), finite=(x,lo,hi)=>typeof x==='number'&&Number.isFinite(x)&&x>=lo&&x<=hi, txt=(x,n=120)=>typeof x==='string'?x.replace(/[\u0000-\u001f\u007f]/g,' ').slice(0,n):'', clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function rng(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function questions(key,seed){const r=rng(seed);if(MODIDS.has(key))return shuffle(MODS.find(m=>m.id===key).questions,r);if(key!=='final')return[];let out=MODS.map(m=>m.questions[Math.floor(r()*m.questions.length)]);for(const m of shuffle(MODS,r).slice(0,8)){const rest=m.questions.filter(q=>!out.some(o=>o.id===q.id));out.push(rest[Math.floor(r()*rest.length)]);}return shuffle(out,r);}
function number(s){if(typeof s!=='string'&&typeof s!=='number')return null;const t=String(s).trim().replace(/−/g,'-');if(!/^[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?$/.test(t))return null;const n=Number(t);return Number.isFinite(n)?n:null;}
function response(q,a){if(q.type==='mc')return Number.isInteger(a)&&a>=0&&a<q.options.length?a:null;if(q.type==='ms')return Array.isArray(a)?[...new Set(a.filter(x=>Number.isInteger(x)&&x>=0&&x<q.options.length))].sort((a,b)=>a-b):[];return typeof a==='string'?txt(a,50):finite(a,-1e12,1e12)?String(a):null;}
function grade(q,a){a=response(q,a);if(q.type==='mc')return a===q.answer?1:0;if(q.type==='ms'){let good=new Set(q.answer),C=good.size,I=q.options.length-C;if(!C)return 0;let tp=a.filter(x=>good.has(x)).length,fp=a.length-tp;return clamp(I?tp/C-fp/I:tp/C,0,1);}let n=number(a);return n!==null&&Math.abs(n-q.answer)<=q.tol+1e-12?1:0;}
function answered(q,a){a=response(q,a);return q.type==='ms'?a.length>0:q.type==='num'?number(a)!==null:a!==null;}
function stamp(x){return typeof x==='string'&&x.length<=40&&Number.isFinite(Date.parse(x))?new Date(x).toISOString():null;}
function blank(){return {schema:'ai101-progress',schemaVersion:1,courseId:CFG.id,courseVersion:CFG.version,created:new Date().toISOString(),profile:{name:'',sid:''},settings:{theme:'system',instructor:'',institution:''},lessons:{},attempts:{},drafts:{},cards:{},project:{topic:'',decision:'',data:'',split:'',baseline:'',checks:'',limits:'',disclosure:''},view:'#/home'};}
function scoreAttempt(key,seed,answers,ts=new Date().toISOString()){let qs=questions(key,seed),points=qs.map(q=>grade(q,answers[q.id]));return {seed,ts,answers:Object.fromEntries(qs.map(q=>[q.id,response(q,answers[q.id])])),score:100*points.reduce((s,p)=>s+p,0)/qs.length};}
function normalize(o){if(!obj(o)||o.schema!=='ai101-progress'||o.schemaVersion!==1||o.courseId!==CFG.id)throw Error('This is not a supported AI 101 progress export.');const p=blank();p.created=stamp(o.created)||p.created;if(obj(o.profile)){p.profile={name:txt(o.profile.name,80),sid:txt(o.profile.sid,40)};}if(obj(o.settings)){p.settings={theme:['system','light','dark'].includes(o.settings.theme)?o.settings.theme:'system',instructor:txt(o.settings.instructor,120),institution:txt(o.settings.institution,120)};}if(obj(o.lessons))for(const k of LESSONS)if(o.lessons[k]===true)p.lessons[k]=true;
for(const key of [...MODIDS,'final']){if(obj(o.attempts)&&Array.isArray(o.attempts[key])){let a=o.attempts[key].filter(x=>obj(x)&&Number.isInteger(x.seed)&&finite(x.seed,0,4294967295)&&stamp(x.ts)&&obj(x.answers)).map(x=>scoreAttempt(key,x.seed,x.answers,stamp(x.ts)));if(a.length>200){const best=a.reduce((b,x)=>x.score>b.score?x:b);a=a.slice(-199);if(!a.includes(best))a.unshift(best);}p.attempts[key]=a;}if(obj(o.drafts)&&obj(o.drafts[key])){let d=o.drafts[key];if(Number.isInteger(d.seed)&&finite(d.seed,0,4294967295)&&obj(d.answers))p.drafts[key]={seed:d.seed,answers:Object.fromEntries(questions(key,d.seed).map(q=>[q.id,response(q,d.answers[q.id])]))};}}
if(obj(o.cards))for(const t of TERMS){const c=o.cards[t.id];if(obj(c))p.cards[t.id]={step:Number.isInteger(c.step)?clamp(c.step,-1,4):-1,due:finite(c.due,0,1e15)?c.due:0,reps:Number.isInteger(c.reps)?clamp(c.reps,0,1e6):0};}if(obj(o.project))for(const k in p.project)p.project[k]=txt(o.project[k],4000);p.view=route(o.view).hash;return p;}
function best(p,key){let a=p.attempts[key]||[];return a.length?Math.max(...a.map(x=>x.score)):null;}
function grading(p){const scores=MODS.map(m=>best(p,m.id)),avg=scores.reduce((s,v)=>s+(v??0),0)/MODS.length,f=best(p,'final'),overall=.7*avg+.3*(f??0);return {scores,avg,final:f,overall,band:overall>=90?'Distinction':overall>=80?'Merit':overall>=70?'Pass':'Not yet completed',eligible:scores.every(x=>x!==null&&x>=70)&&f!==null&&f>=70};}
function route(hash){let h=typeof hash==='string'?hash:'';let a=h.match(/^#\/m\/(\d{1,2})(?:\/(\d|quiz|cards))?$/);if(a){let n=+a[1],sub=a[2]||'1';if(n>=1&&n<=16&&['1','2','3','quiz','cards'].includes(sub))return {type:'module',n,sub,hash:`#/m/${n}/${sub}`};}if(/^#\/(home|glossary|cards|labs|project|final|progress|data|settings|certificate|sources)$/.test(h))return {type:h.slice(2),hash:h};return {type:'home',hash:'#/home'};}
globalThis.AI101Core={CFG,MODS,QB,TERMS,questions,number,response,grade,answered,blank,normalize,scoreAttempt,best,grading,route};
let P=blank(),storageOK=false,cardId=null,flipped=false,activeFilter='all';
const $=s=>document.querySelector(s);
function E(tag,a={},...kids){let e=document.createElement(tag);for(const[k,v]of Object.entries(a)){if(k==='text')e.textContent=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2),v);else if(['value','checked','disabled','hidden'].includes(k))e[k]=v;else e.setAttribute(k,v);}for(let k of kids.flat()){if(k!==null&&k!==undefined)e.append(k instanceof Node?k:document.createTextNode(String(k)));}return e;}
const B=(text,fn,cls='btn')=>E('button',{type:'button',class:cls,text,onclick:fn});
function go(h){location.hash=route(h).hash;}
function save(){P.view=route(location.hash).hash;if(storageOK)try{localStorage.setItem(KEY,JSON.stringify(P));}catch(e){storageOK=false;storageBanner();}navStats();}
function storageBanner(){const e=$('#storage');e.hidden=storageOK;e.textContent='Browser storage is unavailable. Work remains in this tab; export progress before closing. Import your export next time.';}
function message(s){$('#status').textContent=s;}
function download(name,data,type='text/plain'){const blob=new Blob([data],{type}),u=URL.createObjectURL(blob),a=E('a',{href:u,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);message('Download prepared: '+name);}
function theme(){if(P.settings.theme==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=P.settings.theme;$('#theme').textContent='Theme: '+P.settings.theme;}
function confirmAction(text,fn){let d=E('dialog',{'aria-labelledby':'confirm-title'},E('h2',{id:'confirm-title',text:'Please confirm'}),E('p',{text}));let prev=document.activeElement;function close(){d.close();d.remove();if(prev?.isConnected)prev.focus();}let cancel=B('Cancel',close),ok=B('Continue',()=>{close();fn();},'btn primary');d.append(E('div',{class:'actions'},cancel,ok));d.addEventListener('cancel',e=>{e.preventDefault();close();});document.body.append(d);d.showModal();cancel.focus();}
function prose(host,text){for(let p of text.trim().split(/\n\s*\n/))host.append(E('p',{text:p.trim()}));}
function title(host,k,t,desc){host.append(E('p',{class:'eyebrow',text:k}),E('h1',{text:t}));if(desc)host.append(E('p',{class:'lede',text:desc}));}
function link(text,h,cls=''){return E('a',{href:h,class:cls,text});}
function navStats(){let g=grading(P);$('#grade').textContent=g.overall.toFixed(1)+'%';$('#lesson-count').textContent=Object.keys(P.lessons).length+'/48 lessons';document.querySelectorAll('#outline a').forEach(a=>a.setAttribute('aria-current',route(location.hash).type==='module'&&a.dataset.n===String(route(location.hash).n)?'page':'false'));}
function render(){const host=$('#main');host.replaceChildren();let r=route(location.hash);P.view=r.hash;const f={home:home,glossary:glossary,cards:cards,labs:labs,project:project,final:finalPage,progress:progress,data:dataPage,settings:settings,certificate:certificate,sources:sources,module:modulePage}[r.type];f(host,r);navStats();document.title=(r.type==='module'?MODS[r.n-1].title:r.type[0].toUpperCase()+r.type.slice(1))+' · AI 101';}
function home(h){title(h,'A foundation for mechanical engineers','AI 101','Understand the vocabulary. Try the ideas. Check the evidence.');let hero=E('div',{class:'hero-grid'},E('div',{},E('h2',{text:'Physics + data + engineering judgment'}),E('p',{text:'A beginner course in 16 modules: short lessons, offline activities, knowledge checks and four notebook labs. No prior AI or Python experience is assumed.'}),E('div',{class:'actions'},link('Start learning →','#/m/1/1','btn primary'),link('View your progress','#/progress','btn'))),E('div',{class:'hero-facts'},E('strong',{text:'16 modules'}),E('span',{text:'48 lessons · 128 quiz items'}),E('strong',{text:'Learn at your pace'}),E('span',{text:'Planning estimate: 18–24 hours including practice; your time may differ.'})));h.append(hero);
h.append(E('h2',{text:'What you will be able to do'}));let ul=E('ul');['Explain key AI/ML terms using an engineering example.','Choose between physics, data-driven and hybrid approaches.','Interpret basic regression and fault-detection evidence.','Spot leakage, unsupported claims and operating-domain limits.','Use an AI assistant with independent verification and disclosure.'].forEach(s=>ul.append(E('li',{text:s})));h.append(ul);
h.append(E('div',{class:'notice'},E('strong',{text:'Two kinds of evidence'}),E('p',{text:'Browser quizzes check knowledge. The notebook mini-project and rubric provide separate practical evidence for instructor or peer review. Client-side results are self-reported; answer keys are visible.'})));
let grid=E('div',{class:'module-grid'});for(let m of MODS){let score=best(P,m.id);grid.append(link('Module '+m.num+' · '+m.title+'\n'+(score===null?'Begin or resume':`Best quiz: ${score.toFixed(1)}%`),`#/m/${m.num}/1`,'module-tile'));}h.append(E('h2',{text:'Your learning route'}),grid,E('h2',{text:'How to use this course'}));prose(h,'Read the three lessons in a module, try its activity, explain its vocabulary in your own words, and take the quiz. Return to feedback and spaced flashcards when a distinction is unclear.\n\nDownload starter notebooks from Labs and run them locally after installing the environment. Python runs in those notebooks, not in this page. The core lessons and notebook downloads are embedded. Supplementary audio and infographics use the companion media folder; keep it beside this HTML file for offline use. YouTube videos require internet access.');}
function modulePage(h,r){let m=MODS[r.n-1];title(h,'Module '+m.num+' / 16',m.title);let tabs=E('nav',{'aria-label':'Module sections',class:'tabs'});m.lessons.forEach((l,i)=>tabs.append(link((P.lessons[l.id]?'✓ ':'')+(i+1)+'. '+l.title,`#/m/${m.num}/${i+1}`,r.sub===String(i+1)?'active':'')));tabs.append(link('Quiz',`#/m/${m.num}/quiz`,r.sub==='quiz'?'active':''),link('Flashcards',`#/m/${m.num}/cards`,r.sub==='cards'?'active':''));h.append(tabs);if(r.sub==='quiz'){let region=E('div');h.append(region);quiz(region,m.id);return;}if(r.sub==='cards'){deck(h,m.id);return;}let l=m.lessons[+r.sub-1];h.append(E('h2',{text:l.title}));let outcomes=E('details',{},E('summary',{text:'Module learning outcomes'}));let ul=E('ul');m.outcomes.forEach(o=>ul.append(E('li',{text:o})));outcomes.append(ul);h.append(outcomes);prose(h,l.text);
const media={m01l1:{video:'5PXqVJoDBgI',audio:'media/1_1-The_Math_Behind_Industrial_AI.m4a',image:'media/1_1-Relationships_Among_AI_Concepts.png',alt:'Relationships among AI concepts infographic'},m01l2:{video:'FSDlKaTM3Ws',audio:'media/1_2-How_Engineers_Distinguish_AI_From_Automation.m4a',image:'media/1_2-Automation_and_AI_Engineering_Concepts.png',alt:'Automation and AI engineering concepts infographic'},m01l3:{video:'MOJL4aPNaBY',audio:'media/1_3-Engineering_Decisions_Must_Come_Before_AI.m4a',image:'media/1_3-Defining_an_Engineering_Decision.png',alt:'Defining an engineering decision infographic'}};
let extra=media[l.id];if(extra){
let box=E('section',{class:'learning-media','aria-label':'Lesson learning resources'});
const resourceLink=(text,href,download=false)=>E('a',{href,target:'_blank',rel:'noopener',...(download?{download:''}:{}),text});
box.append(E('h3',{text:'Infographic'}),E('img',{src:extra.image,alt:extra.alt,loading:'lazy'}),E('p',{class:'small'},resourceLink('Open full-size infographic',extra.image)));
let slides='media/'+m.num+'_'+r.sub+'.pdf';
box.append(E('h3',{text:'Lesson slides'}),E('p',{class:'small'},resourceLink('Open slides',slides),' · ',resourceLink('Download slides',slides,true)),E('iframe',{class:'slides-frame',title:'Lesson '+m.num+'.'+r.sub+' slides: '+l.title,src:slides,loading:'lazy'}));
box.append(E('h3',{text:'Video Session'}),E('p',{class:'small',text:'Watch the lesson video below. Internet access is required.'}),E('div',{class:'video-frame'},E('iframe',{title:'Lesson '+m.num+'.'+r.sub+' video: '+l.title,referrerpolicy:'strict-origin-when-cross-origin',src:'https://www.youtube-nocookie.com/embed/'+extra.video,loading:'lazy',allow:'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture',allowfullscreen:true})),E('p',{class:'small'},resourceLink('Watch on YouTube','https://www.youtube.com/watch?v='+extra.video)));
box.append(E('h3',{text:'Audio narration'}),E('audio',{id:'lesson-audio-'+l.id,'aria-label':'Lesson '+m.num+'.'+r.sub+' audio narration',controls:true,preload:'metadata',src:extra.audio}),E('p',{class:'small'},resourceLink('Open audio narration',extra.audio)));h.append(box);
}
let check=E('div',{class:'notice'},E('h3',{text:'Pause and explain'}),E('p',{text:l.check}),E('p',{class:'small',text:'Use an engineering example and state your assumptions. These reflection answers are not automatically graded.'}));h.append(check);
if(r.sub==='2')activity(h,m.demo,m.num);if(r.sub==='3'){h.append(E('h2',{text:'Terms to explain'}));let dl=E('dl',{class:'terms'});m.terms.forEach(t=>dl.append(E('dt',{text:t.term}),E('dd',{},E('p',{text:t.definition}),E('p',{class:'example',text:'Example: '+t.example}))));h.append(dl);}
let cb=E('input',{type:'checkbox',checked:!!P.lessons[l.id]});cb.onchange=()=>{if(cb.checked)P.lessons[l.id]=true;else delete P.lessons[l.id];save();message(cb.checked?'Lesson marked complete.':'Lesson completion removed.');};h.append(E('label',{class:'complete'},cb,' Mark as complete'));
let next=+r.sub<3?`#/m/${m.num}/${+r.sub+1}`:`#/m/${m.num}/quiz`;h.append(E('div',{class:'actions'},link('Next →',next,'btn primary'),m.num>1?link('Previous module',`#/m/${m.num-1}/1`,'btn'):null));}
function rule(q){if(q.type==='mc')return 'Choose one. Correct = 1 point; otherwise 0.';if(q.type==='ms')return 'Select all that apply. Score = max(0, TP/C − FP/I), where C/I are counts of correct/incorrect options. Select-all earns 0 when both classes exist.';return `Enter a plain number in ${q.unit}. Accepted absolute tolerance: ±${q.tol} ${q.unit}. Boundaries are accepted. Keep enough digits to fit this tolerance; omit unit text.`;}
function answerText(q,a){if(q.type==='mc')return a===null?'No answer':q.options[a];if(q.type==='ms')return a.length?a.map(i=>q.options[i]).join('; '):'No answer';return a??'No answer';}
function correctText(q){return q.type==='mc'?q.options[q.answer]:q.type==='ms'?q.answer.map(i=>q.options[i]).join('; '):q.answer.toFixed(q.tol&&q.tol<1?3:0)+' '+q.unit;}
function qel(q,i,seed,given,change,review=false){let box=E('section',{class:'question'},E('p',{class:'eyebrow',text:'Question '+(i+1)}));let fs=E('fieldset',{},E('legend',{text:q.stem}),E('p',{class:'small',id:q.id+'help',text:rule(q)}));let a=response(q,given);if(q.type==='num'){let id=q.id+'input',inp=E('input',{id,type:'text',inputmode:'decimal',value:a??'',disabled:review,'aria-describedby':q.id+'help',autocomplete:'off'});inp.oninput=()=>change(inp.value);fs.append(E('label',{for:id,text:'Answer ('+q.unit+')'}),inp);}else{let order=shuffle(q.options.map((_,i)=>i),rng((seed^q.id.split('').reduce((s,c)=>s+c.charCodeAt(0),0))>>>0));for(let oi of order){let input=E('input',{type:q.type==='mc'?'radio':'checkbox',name:q.id,value:oi,disabled:review,checked:q.type==='mc'?a===oi:a.includes(oi)});input.onchange=()=>change(q.type==='mc'?oi:[...fs.querySelectorAll('input:checked')].map(x=>+x.value));fs.append(E('label',{class:'option'},input,E('span',{text:q.options[oi]})));}}box.append(fs);if(review){let p=grade(q,given);box.append(E('div',{class:'feedback '+(p===1?'good':'review')},E('strong',{text:p===1?'Correct':p>0?'Partly correct · '+Math.round(p*100)+'% credit':'Review this concept'}),E('p',{text:'Your answer: '+answerText(q,a)}),E('p',{text:'Correct: '+correctText(q)}),E('p',{text:q.explain})));}return box;}
function quiz(h,key,reviewIndex=null){const list=P.attempts[key]||[],b=best(P,key),d=P.drafts[key];h.append(E('div',{class:'notice'},E('p',{text:(key==='final'?'24 questions: at least one from every module plus eight additional bank items.':'8 questions covering this module.')+' Each item has equal weight. Best attempt counts; pass mark 70%.'}),E('p',{text:'Retakes reorder and sample bank items. Equivalent difficulty is not empirically established. Keys are visible in the offline source. Unanswered items earn zero.'}),E('p',{text:'Best: '+(b===null?'not attempted':b.toFixed(1)+'%')+' · Attempts: '+list.length})));
if(reviewIndex!==null){let a=list[reviewIndex];h.append(E('h2',{text:'Attempt '+(reviewIndex+1)+' · '+a.score.toFixed(1)+'%'}));questions(key,a.seed).forEach((q,i)=>h.append(qel(q,i,a.seed,a.answers[q.id],()=>{},true)));h.append(B('Back to overview',()=>{h.replaceChildren();quiz(h,key);}));return;}
if(!d){h.append(B('Start '+(list.length?'another':'your first')+' attempt',()=>{P.drafts[key]={seed:Math.floor(Math.random()*4294967296),answers:{}};save();h.replaceChildren();quiz(h,key);},'btn primary'));if(list.length){h.append(E('h2',{text:'Attempt history'}));list.slice().reverse().forEach((a,j)=>h.append(E('div',{class:'history'},E('span',{text:'Attempt '+(list.length-j)+' · '+new Date(a.ts).toLocaleString()+' · '+a.score.toFixed(1)+'%'}),B('Review',()=>{h.replaceChildren();quiz(h,key,list.length-1-j);}))));}return;}
h.append(E('h2',{text:'Attempt in progress'}),E('p',{class:'small',text:'Answers and the seeded question selection are preserved in progress exports and browser storage when available.'}));let qs=questions(key,d.seed);qs.forEach((q,i)=>h.append(qel(q,i,d.seed,d.answers[q.id],a=>{d.answers[q.id]=a;save();})));h.append(E('div',{class:'actions'},B('Submit answers',()=>{let missing=qs.filter(q=>!answered(q,d.answers[q.id])).length;confirmAction((missing?missing+' unanswered or invalid responses will earn zero. ':'')+'Submit this attempt? Submitted answers cannot be changed.',()=>{let a=scoreAttempt(key,d.seed,d.answers);(P.attempts[key]??=[]).push(a);delete P.drafts[key];save();h.replaceChildren();quiz(h,key,P.attempts[key].length-1);h.scrollIntoView({block:'start'});});},'btn primary'),B('Discard draft',()=>confirmAction('Discard only this unfinished attempt? Submitted history is kept.',()=>{delete P.drafts[key];save();h.replaceChildren();quiz(h,key);})))) ;}
function finalPage(h){title(h,'Knowledge assessment','Final assessment','Complete the modules first, then check your understanding across the whole course.');let region=E('div');h.append(region);quiz(region,'final');}
function glossary(h){title(h,'Vocabulary','Engineering AI glossary',TERMS.length+' terms with plain-language definitions and engineering examples.');let input=E('input',{type:'search',id:'term-search',placeholder:'Try “training”, “RAG” or “fault”'});h.append(E('label',{for:'term-search',text:'Search terms and examples'}),input);let result=E('div');h.append(result);function draw(){result.replaceChildren();let s=input.value.toLowerCase(),a=TERMS.filter(t=>(t.term+' '+t.definition+' '+t.example).toLowerCase().includes(s));result.append(E('p',{class:'small',text:a.length+' matching terms'}));for(let t of a)result.append(E('section',{class:'glossary-entry'},E('h2',{text:t.term}),E('p',{text:t.definition}),E('p',{class:'example',text:t.example}),link('Module '+MODS.find(m=>m.id===t.module).num,`#/m/${MODS.find(m=>m.id===t.module).num}/3`)));}input.oninput=draw;draw();}
function cards(h){title(h,'Spaced practice','Flashcard review','Explain the term before revealing its definition. A rating schedules practice; it does not affect grades.');deck(h,null);}
function deck(h,mod){let select=E('select',{id:'deck-filter'});select.append(E('option',{value:'all',text:'All terms'}),E('option',{value:'due',text:'Due now'}));MODS.forEach(m=>select.append(E('option',{value:m.id,text:'Module '+m.num+' · '+m.title})));select.value=mod||activeFilter;h.append(E('label',{for:'deck-filter',text:'Choose a deck'}),select);let host=E('div');h.append(host);function pool(){let v=select.value;return TERMS.filter(t=>v==='all'||v==='due'&&(!P.cards[t.id]||P.cards[t.id].due<=Date.now())||t.module===v);}function draw(focus=false){host.replaceChildren();let a=pool();if(!a.length){host.append(E('p',{text:'No cards are due in this deck. Select all terms for extra practice.'}));return;}if(!a.some(t=>t.id===cardId)){cardId=a[0].id;flipped=false;}let t=TM.get(cardId),i=a.findIndex(x=>x.id===cardId),flip=B(flipped?'Hide definition':'Reveal definition',()=>{flipped=!flipped;draw(true);},'btn primary');host.append(E('div',{class:'flashcard'},E('p',{class:'eyebrow',text:(i+1)+' / '+a.length}),E('h2',{text:t.term}),E('p',{text:flipped?t.definition:'Explain this term in your own words and give an ME example.'}),flipped?E('p',{class:'example',text:t.example}):null,flip));if(flipped){let rates=E('div',{class:'actions'});for(let [v,label]of [['again','Again · 10 min'],['hard','Hard · current interval'],['good','Good · next interval']])rates.append(B(label,()=>{let c=P.cards[t.id]||{step:-1,due:0,reps:0};if(v==='good')c.step=Math.min(c.step+1,4);let days=v==='again'?10/1440:[1,3,7,16,35][Math.max(c.step,0)];c.due=Date.now()+days*864e5;c.reps++;P.cards[t.id]=c;save();flipped=false;cardId=a[(i+1)%a.length].id;draw(true);}));host.append(rates);}host.append(E('div',{class:'actions'},B('Previous',()=>{cardId=a[(i-1+a.length)%a.length].id;flipped=false;draw(true);}),B('Next',()=>{cardId=a[(i+1)%a.length].id;flipped=false;draw(true);})),E('p',{class:'small',text:'Good advances through 1, 3, 7, 16 and 35 days. Again schedules 10 minutes; Hard retains the current interval (minimum 1 day).'}));if(focus)host.querySelector('button').focus();}select.onchange=()=>{activeFilter=select.value;cardId=null;draw();};draw();}
function labs(h){title(h,'Beginner practical work','Four notebook labs','Download a starter, run it locally, and compare with the complete reference after your attempt. No Python executes in this page.');h.append(E('div',{class:'notice'},E('p',{text:'All data are synthetic teaching examples. Install the target environment once: Python 3.10+ with NumPy 1.26+ and optional JupyterLab. Reference execution versions and results are recorded in the companion validation summary.'}),E('pre',{text:'python -m pip install numpy jupyterlab\njupyter lab'}),B('Download environment requirements',()=>download('AI_101_requirements.txt',DATA.environment))));for(let l of DATA.labs){h.append(E('section',{class:'lab'},E('h2',{text:l.title}),E('p',{text:l.purpose}),E('div',{class:'actions'},B('Download starter',()=>download(l.id+'_starter.ipynb',JSON.stringify(l.starter,null,2),'application/x-ipynb+json'),'btn primary'),B('Download reference',()=>download(l.id+'_reference.ipynb',JSON.stringify(l.reference,null,2),'application/x-ipynb+json'))),E('p',{class:'small',text:'Starters contain named TODOs that intentionally raise NotImplementedError. Complete them before a clean Run All. References contain complete implementations; they are not evidence of your own work.'})));}h.append(link('Mini-project and rubric →','#/project','btn'));}
const PROJECT_LABELS={topic:'Project topic',decision:'Decision, users, features and target',data:'Data provenance, units and operating domain',split:'Training / validation / final-test plan',baseline:'Baseline and comparison metric',checks:'Known-case / physical checks and results',limits:'Limitations and required additional evidence',disclosure:'Reproducibility and permitted AI-use disclosure'};
function project(h){title(h,'Separate practical assessment','Your engineering mini-project','Plan, carry out and explain one bounded study. The browser saves your plan but does not grade or verify your notebooks.');let table=E('table',{},E('caption',{text:'Instructor or peer-review rubric'}),E('thead',{},E('tr',{},E('th',{text:'Evidence'}),E('th',{text:'Weight'}))),E('tbody'));for(let [a,b]of [['Problem/data: clear decision, available inputs and provenance','20%'],['Baseline/split/preprocessing: justified boundaries and fair comparison','25%'],['Evaluation/interpretation: relevant metrics and error consequences','25%'],['Physical verification/limitations: known-case checks and scope','20%'],['Reproducibility/disclosure: clean run, versions and permitted AI assistance','10%']])table.lastChild.append(E('tr',{},E('td',{text:a}),E('td',{text:b})));h.append(table,E('h2',{text:'Saved project plan'}));for(let[k,label]of Object.entries(PROJECT_LABELS)){let ta=E('textarea',{id:'proj-'+k,rows:3,maxlength:4000,value:P.project[k]});ta.oninput=()=>{P.project[k]=ta.value;save();};h.append(E('label',{for:ta.id,text:label}),ta);}h.append(E('div',{class:'actions'},B('Download plan and rubric',()=>download('AI_101_project_plan.md',projectText())),B('Download submission checklist',()=>download('AI_101_submission_checklist.md',DATA.checklist))));h.append(E('h2',{text:'Outcome-to-evidence map'}));for(let[a,b]of [['Data vocabulary and screening','Lab 1 arrays, unit table and flagged-row audit.'],['Regression, baselines and evaluation','Lab 2 validation selection, locked test metrics and physics comparison.'],['Fault metrics and decision consequences','Lab 3 threshold evidence, confusion matrix and baseline interpretation.'],['Responsible use and independent verification','Lab 4 corrected calculation, source status and assumptions.'],['Practical integration','Your mini-project notebook, report, clean-run outputs and oral explanation.']])h.append(E('p',{},E('strong',{text:a+': '}),b));}
function projectText(){return '# AI 101 mini-project plan\n\n'+Object.entries(PROJECT_LABELS).map(([k,l])=>'## '+l+'\n\n'+P.project[k]).join('\n\n')+'\n\n'+DATA.checklist;}
function progress(h){let g=grading(P);title(h,'Your evidence','Progress and grades','Knowledge scores use unrounded values. Practical notebook evidence is assessed separately.');h.append(E('div',{class:'score-grid'},E('div',{},E('strong',{text:g.overall.toFixed(1)+'%'}),E('span',{text:'Overall · '+g.band})),E('div',{},E('strong',{text:g.avg.toFixed(1)+'%'}),E('span',{text:'Mean best module score · 70% weight'})),E('div',{},E('strong',{text:g.final===null?'—':g.final.toFixed(1)+'%'}),E('span',{text:'Best final · 30% weight'}))));let table=E('table',{},E('caption',{text:'Module completion and best quiz scores'}),E('thead',{},E('tr',{},E('th',{text:'Module'}),E('th',{text:'Read'}),E('th',{text:'Best'}),E('th',{text:'Attempts'})))),tb=E('tbody');MODS.forEach((m,i)=>tb.append(E('tr',{},E('td',{},link(m.num+'. '+m.title,`#/m/${m.num}/1`)),E('td',{text:m.lessons.filter(l=>P.lessons[l.id]).length+'/3'}),E('td',{text:g.scores[i]===null?'—':g.scores[i].toFixed(1)+'%'}),E('td',{text:(P.attempts[m.id]||[]).length}))));table.append(tb);h.append(E('div',{class:'table-wrap'},table),E('p',{text:'Unattempted quizzes count as zero in the average. Grade bands: ≥90 Distinction; ≥80 Merit; ≥70 Pass; below 70 Not yet completed. Every module quiz and final needs ≥70% for a browser completion record.'}),E('p',{class:'notice',text:g.eligible?'All browser knowledge requirements met. This is self-reported, unauthenticated evidence; it does not certify the mini-project.':'Browser completion requirements remain. Read feedback and retake the relevant knowledge checks.'}),E('div',{class:'actions'},link('Completion record','#/certificate','btn primary'),B('Download progress report',()=>download('AI_101_progress_report.md',report())),link('Practical rubric','#/project','btn')));}
function report(){let g=grading(P);return '# AI 101 knowledge progress\n\nStudent: '+P.profile.name+'\nID: '+P.profile.sid+'\nCourse '+CFG.id+' v'+CFG.version+'\nGenerated '+new Date().toISOString()+'\nOverall: '+g.overall.toFixed(2)+'% ('+g.band+')\nEligible: '+g.eligible+'\n\n'+MODS.map(m=>m.num+'. '+m.title+': '+(best(P,m.id)??'not attempted')+'%').join('\n')+'\n\nFinal: '+(g.final??'not attempted')+'%\n\nSelf-reported client-side knowledge results. Keys and storage are editable. Notebook and report competence is assessed separately; no hardware validation or identity authentication is implied.';}
function certificate(h){let g=grading(P);title(h,'Self-reported knowledge record','Browser completion record','This records browser knowledge checks. It is not an authenticated credential or a practical engineering qualification.');if(!g.eligible){h.append(E('p',{text:'Pass every module quiz and the final at 70% or above first.'}),link('View requirements','#/progress','btn'));return;}if(!P.profile.name.trim()){h.append(E('p',{text:'Set your name before preparing the record.'}),link('Set name','#/settings','btn'));return;}let c=E('section',{class:'certificate'},E('p',{class:'eyebrow',text:'AI 101 · Mechanical engineering'}),E('h2',{text:'Knowledge course completion'}),E('h3',{text:P.profile.name}),E('p',{text:P.profile.sid?'Student ID: '+P.profile.sid:''}),E('p',{text:'Completed the browser knowledge assessments for AI 101 for Mechanical Engineers.'}),E('p',{text:'Overall '+g.overall.toFixed(1)+'% · '+g.band}),E('p',{text:'Course '+CFG.id+' · version '+CFG.version}),E('p',{text:P.settings.instructor||CFG.instructor}),E('p',{text:P.settings.institution||CFG.institution}),E('p',{class:'small',text:'Record generated '+new Date().toISOString().slice(0,10)+'. No historical completion date is inferred. Self-reported results; visible answer keys and editable client-side storage. Practical work is assessed separately.'}));h.append(c,E('div',{class:'actions no-print'},B('Print / save as PDF',()=>window.print(),'btn primary'),B('Download JSON record',()=>download('AI_101_completion_record.json',JSON.stringify({record:'ai101-knowledge',courseId:CFG.id,version:CFG.version,generated:new Date().toISOString(),student:P.profile,grade:g,practicalVerified:false,caveat:'Self-reported, unauthenticated browser knowledge record; practical assessment separate.'},null,2),'application/json'))));}
function settings(h){title(h,'Local configuration','Profile and settings','Names and instructor details are stored locally and rendered as text.');for(let[key,label,max]of [['name','Student name',80],['sid','Student ID',40]]){let i=E('input',{id:'profile-'+key,maxlength:max,value:P.profile[key]});i.oninput=()=>{P.profile[key]=txt(i.value,max);save();};h.append(E('label',{for:i.id,text:label}),i);}for(let[key,label]of [['instructor','Instructor (optional override)'],['institution','Institution (optional override)']]){let i=E('input',{id:'setting-'+key,maxlength:120,value:P.settings[key],placeholder:CFG[key]});i.oninput=()=>{P.settings[key]=txt(i.value,120);save();};h.append(E('label',{for:i.id,text:label}),i);}h.append(E('p',{class:'notice',text:'This file does not send names, answers or project plans to a service. Exported progress includes your local profile and work; share it deliberately. Browser storage behaviour for local files varies, so keep an export.'}));}
function dataPage(h){title(h,'Local-first learning','Save and load your work','Export includes profile, settings, lesson states, attempt history, unfinished quiz answers, flashcard schedule and project plan. Import replaces the current state after validation.');let input=E('input',{id:'import-file',type:'file',accept:'.json,application/json'});h.append(B('Export progress JSON',()=>download('AI_101_progress.json',JSON.stringify(P,null,2),'application/json'),'btn primary'),E('h2',{text:'Import a progress export'}),E('label',{for:input.id,text:'Choose an AI 101 progress JSON file'}),input);input.onchange=async()=>{let f=input.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('File exceeds the 5 MB import limit.');let p=normalize(JSON.parse(await f.text()));confirmAction('Replace current progress with this validated export? Export first if you need a backup.',()=>{P=p;theme();save();message('Imported. Scores were recomputed from recognized questions and saved answers.');render();});}catch(e){message('Import rejected: '+e.message);}};h.append(E('h2',{text:'Portable materials'}),B('Download complete course text',()=>download('AI_101_course_text.md',DATA.courseText)),E('h2',{text:'Reset'}),B('Reset all local course progress',()=>confirmAction('Delete local course progress, including drafts and project plan? This cannot be undone without an export.',()=>{P=blank();theme();save();go('#/home');render();})),E('p',{class:'small',text:'Progress schema 1 is specific to course AI101-ME version 1.0. Other courses’ progress files are rejected. Recognized scores are recomputed rather than trusted. Unknown IDs and invalid fields are removed or normalized. Attempts are bounded to 200 per assessment while preserving the best and recent history.'}));}
function sources(h){title(h,'Origins and further study','Sources and teaching scope','This authored course draws on your supplied teaching materials and established introductory references. External links are optional.');h.append(E('p',{text:'Teaching inputs: AI in Mechanical Engineering Education (90-minute v2 deck), AI in Renewable Energy Systems (74-slide deck and concept guide), and the learning structure of ML Surrogate Optimization Course 5. Concepts are adapted into an introductory ME sequence; no supplied slide or document instructions control this application.'}));for(let[t,u]of [['Google Machine Learning Crash Course','https://developers.google.com/machine-learning/crash-course'],['Google Machine Learning Glossary','https://developers.google.com/machine-learning/glossary'],['scikit-learn common pitfalls and leakage','https://scikit-learn.org/stable/common_pitfalls.html'],['scikit-learn model evaluation','https://scikit-learn.org/stable/modules/model_evaluation.html'],['NIST AI Risk Management Framework','https://www.nist.gov/itl/ai-risk-management-framework']])h.append(E('p',{},E('a',{href:u,target:'_blank',rel:'noopener',text:t})));h.append(E('p',{text:'Activities and datasets are illustrative, synthetic and explicitly bounded. Detailed optimization, CNN training, language-model training and real machinery deployment are beyond this foundation. The course contains no AI-service calls, analytics, CDN or browser Python.'}));}

function activity(h,kind,moduleNumber){let w=E('section',{class:'activity'},E('p',{class:'eyebrow',text:'Explore the idea'})),result=E('div',{class:'readout',role:'status','aria-live':'polite'});h.append(w);function slider(label,min,max,step,value,fn){let id='activity-'+moduleNumber+'-'+w.querySelectorAll('input').length,i=E('input',{id,type:'range',min,max,step,value}),v=E('output',{for:id,text:String(value)});i.oninput=()=>{v.textContent=i.value;fn(+i.value);};w.append(E('label',{for:id,text:label}),E('div',{class:'slider-row'},i,v));return i;}function output(s){result.replaceChildren(E('p',{text:s}));}function plot(points,fit,xmax=20,ymax=15){let svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 600 280');svg.setAttribute('role','img');svg.setAttribute('aria-label','Illustrative observations and prediction line. Numerical metrics are given below.');const sx=x=>50+x/xmax*510,sy=y=>235-y/ymax*205;let path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d','M50 25V235H560');path.setAttribute('class','axes');svg.append(path);for(let [x,y]of points){let c=document.createElementNS(svg.namespaceURI,'circle');c.setAttribute('cx',sx(x));c.setAttribute('cy',sy(y));c.setAttribute('r','5');c.setAttribute('class','point');svg.append(c);}let line=document.createElementNS(svg.namespaceURI,'path');line.setAttribute('d','M'+sx(0)+' '+sy(fit(0))+'L'+sx(xmax)+' '+sy(fit(xmax)));line.setAttribute('class','fit');svg.append(line);result.append(svg);}
if(kind==='line'){w.append(E('h3',{text:'Fit an illustrative temperature-rise line'}),E('p',{text:'Move the coefficients with arrow keys or the pointer. Five synthetic observations use power in W and rise in K. This changes a model, not an experiment.'}));let b=1,k=.6;let pts=[[0,1.2],[5,3.8],[10,7.4],[15,9.6],[20,13.1]];function draw(){let r=pts.map(([x,y])=>y-(b+k*x)),mae=r.reduce((s,v)=>s+Math.abs(v),0)/5,rmse=Math.sqrt(r.reduce((s,v)=>s+v*v,0)/5);output(`ΔT = ${b.toFixed(1)} + ${k.toFixed(2)}P. MAE ${mae.toFixed(3)} K; RMSE ${rmse.toFixed(3)} K. x: power 0–20 W; y: rise 0–15 K. Observations: `+pts.map(p=>p.join(' W → ')+' K').join('; '));plot(pts,x=>b+k*x);}slider('Intercept (K)',0,3,.1,b,v=>{b=v;draw();});slider('Slope (K/W)',.2,.8,.01,k,v=>{k=v;draw();});w.append(result);draw();return;}
if(kind==='threshold'){w.append(E('h3',{text:'Inspect an alarm threshold'}),E('p',{text:'These 12 synthetic scores are illustrative and not calibrated. Positive = fault. Lowering the threshold changes false alarms and missed faults.'}));let scores=[.1,.2,.35,.4,.55,.62,.7,.82,.9,.3,.65,.45],y=[0,0,0,1,0,1,1,1,1,0,0,1];function draw(t){let tp=0,fp=0,fn=0,tn=0;scores.forEach((s,i)=>{let p=s>=t;if(p&&y[i])tp++;else if(p)fp++;else if(y[i])fn++;else tn++;});output(`Threshold ${t.toFixed(2)} · TP ${tp}, FP ${fp}, FN ${fn}, TN ${tn}. Precision ${tp+fp?(100*tp/(tp+fp)).toFixed(1)+'%':'undefined (no alerts)'}, recall ${(100*tp/(tp+fn)).toFixed(1)}%, accuracy ${(100*(tp+tn)/12).toFixed(1)}%.`);}slider('Threshold',0,1,.05,.5,draw);w.append(result);draw(.5);return;}
if(kind==='neuron'){w.append(E('h3',{text:'A neuron you can calculate'}),E('p',{text:'Fixed illustrative inputs x₁=2 and x₂=1. a=ReLU(w₁x₁+w₂x₂+b).'}));let a=.5,b=-1,c=.2;function draw(){let z=a*2+b+c;output(`z = ${a.toFixed(1)}×2 + ${b.toFixed(1)}×1 + ${c.toFixed(1)} = ${z.toFixed(2)}; ReLU output = ${Math.max(0,z).toFixed(2)}.`);}slider('Weight w₁',-2,2,.1,a,v=>{a=v;draw();});slider('Weight w₂',-2,2,.1,b,v=>{b=v;draw();});slider('Bias b',-2,2,.1,c,v=>{c=v;draw();});w.append(result);draw();return;}
if(kind==='scaling'){w.append(E('h3',{text:'Compare two explicitly defined transforms'}),E('p',{text:'Fixed engineering bounds 0–100°C; illustrative training mean 40°C and standard deviation 10°C.'}));function draw(x){output(`Temperature ${x}°C → min–max ${((x-0)/100).toFixed(2)}; standardized ${( (x-40)/10).toFixed(2)}. Original units must still be documented.`);}slider('Temperature (°C)',0,100,1,25,draw);w.append(result);draw(25);return;}
if(kind==='physics'){w.append(E('h3',{text:'A physical baseline'}),E('p',{text:'At fixed pressure rise 100,000 Pa, hydraulic power = ΔpQ. The simplified input-power estimate divides by efficiency.'}));let q=.02,eta=.8;function draw(){output(`Q=${q.toFixed(3)} m³/s · hydraulic power ${(100000*q).toFixed(0)} W · at η=${eta.toFixed(2)}, input power ${(100000*q/eta).toFixed(0)} W. These are stated idealized relationships, not measured plant results.`);}slider('Flow (m³/s)',.005,.03,.001,q,v=>{q=v;draw();});slider('Efficiency',.4,1,.05,eta,v=>{eta=v;draw();});w.append(result);draw();return;}
if(kind==='tree'){w.append(E('h3',{text:'One illustrative tree split'}),E('p',{text:'Rule: vibration RMS above a chosen threshold produces an inspection suggestion. It is not a manufacturer fault limit.'}));let t=3,x=2.5;function draw(){output(`RMS ${x.toFixed(1)} m/s² ${x>t?'>':'≤'} threshold ${t.toFixed(1)} m/s² → ${x>t?'suggest inspection':'no alert from this one rule'}. Investigate operating context and sensor quality.`);}slider('RMS reading (m/s²)',0,6,.1,x,v=>{x=v;draw();});slider('Chosen threshold (m/s²)',0,6,.1,t,v=>{t=v;draw();});w.append(result);draw();return;}
if(kind==='prompt'){w.append(E('h3',{text:'Build a checkable prompt locally'}));let fields={Task:'Estimate DC power of a PV array',Given:'Area 20 m², irradiance 800 W/m², efficiency 0.20',Assumptions:'Ignore temperature and other losses',Output:'Show equations, units, arithmetic and missing information for daily energy',Verification:'Check against ηAG and distinguish power from energy'};for(let[k,v]of Object.entries(fields)){let ta=E('textarea',{rows:2,id:'prompt-'+k,value:v});w.append(E('label',{for:ta.id,text:k}),ta);ta.oninput=()=>fields[k]=ta.value;}w.append(B('Build prompt',()=>{let s=Object.entries(fields).map(([k,v])=>k+': '+v).join('\n');result.replaceChildren(E('pre',{text:s}));}),E('p',{class:'small',text:'No AI service is called. Review this text before using an external assistant.'}),result);return;}
const scenarios={
taxonomy:['A camera classifier labels surface cracks. Is it necessarily generative?',['Yes: all deep models generate content','No: classification is a different task'],1,'A deep model may classify without generating content.'],
data:['One row has flow, pressure, speed and measured power. Predict power. Which is the target?',['Measured power','The CSV file name','All inputs'],0,'Power is the target in this task; the other measured quantities can be features.'],
tasks:['A model reconstructs a masked signal using the original signal as target. Which setup?',['Self-supervised','No learning','Reinforcement only'],0,'The target is generated from the data itself.'],
split:['You want predictions on a new machine. Which evaluation is stronger for that question?',['Randomly mix each machine’s rows','Hold out whole machines'],1,'Match the evaluation boundary to transfer across machines.'],
timeline:['You removed nighttime rows. Does shifting 96 remaining rows necessarily mean 24 hours?',['Yes','No: align by timestamps'],1,'Filtering makes row positions an unreliable clock.'],
context:['Which operation updates model weights?',['Add examples to a prompt','Retrieve a manual','Fine-tune with training examples'],2,'Prompting and retrieval supply inference context; fine-tuning updates parameters.'],
trust:['A synthetic simulator comparison passed. Does that validate real equipment?',['Yes, because the scores are good','No: real-system evidence is still needed'],1,'A synthetic exercise can verify a method, but not establish real-system suitability.'],
project:['A predicted design has a low objective. What is next?',['Report it as the proven optimum','Verify the candidate and constraints with the original model'],1,'Predicted improvements are hypotheses requiring checks.']};let [s,opts,a,feedback]=scenarios[kind]||scenarios.trust;w.append(E('h3',{text:'Make an engineering distinction'}),E('p',{text:s}));opts.forEach((o,i)=>w.append(B(o,()=>output((i===a?'Correct. ':'Reconsider. ')+feedback))));w.append(result);}
function boot(){document.querySelector('.skip').onclick=e=>{e.preventDefault();$('#main').focus();};try{localStorage.setItem(KEY+'-probe','1');localStorage.removeItem(KEY+'-probe');storageOK=true;let raw=localStorage.getItem(KEY);if(raw)P=normalize(JSON.parse(raw));}catch(e){if(storageOK){message('Saved data could not be restored safely; a blank session was opened. Import a valid backup.');}else storageOK=false;}storageBanner();theme();let outline=$('#outline');for(let m of MODS)outline.append(E('a',{href:`#/m/${m.num}/1`,'data-n':m.num,text:String(m.num).padStart(2,'0')+' · '+m.title}));$('#theme').onclick=()=>{let a=['system','light','dark'];P.settings.theme=a[(a.indexOf(P.settings.theme)+1)%3];theme();save();};$('#export').onclick=()=>download('AI_101_progress.json',JSON.stringify(P,null,2),'application/json');window.addEventListener('hashchange',()=>{render();save();$('#main').focus();window.scrollTo({top:0,behavior:'auto'});});if(!location.hash)history.replaceState(null,'',P.view);render();}
if(!globalThis.AI101_TEST)boot();

