const fs=require('fs'),vm=require('vm'),assert=require('assert');
const DATA=JSON.parse(fs.readFileSync('ai101_data.json','utf8'));
const ctx=vm.createContext({DATA,AI101_TEST:true});vm.runInContext(fs.readFileSync('ai101_app.js','utf8'),ctx);const C=ctx.AI101Core;
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
const clone=x=>JSON.parse(JSON.stringify(x));
test('Curriculum IDs and answer keys',()=>{assert.equal(C.MODS.length,16);assert.equal(C.QB.size,128);assert.equal(C.TERMS.length,154);for(let m of C.MODS){assert.equal(m.lessons.length,3);assert.equal(m.questions.length,8);for(let q of m.questions){if(q.type==='mc')assert(q.answer>=0&&q.answer<q.options.length);if(q.type==='ms'){assert(q.answer.length>0&&q.answer.length<q.options.length);assert.equal(new Set(q.answer).size,q.answer.length);}if(q.type==='num')assert(Number.isFinite(q.answer)&&q.tol>=0);let a=q.type==='num'?String(q.answer):q.answer;assert.equal(C.grade(q,a),1,q.id);}}});
test('Final covers all modules for 1000 seeds',()=>{for(let seed=0;seed<1000;seed++){let qs=C.questions('final',seed);assert.equal(qs.length,24);assert.equal(new Set(qs.map(q=>q.id)).size,24);assert.equal(new Set(qs.map(q=>q.id.slice(0,3))).size,16);}});
test('Multiple select fair and bounded',()=>{let q={type:'ms',options:['a','b','c','d'],answer:[0,1,2]};assert.equal(C.grade(q,[0,1,2,3]),0);assert.equal(C.grade(q,[0,0,0]),1/3);assert.equal(C.grade(q,[0,1,2]),1);assert.equal(C.grade(q,[0,3]),0);assert.equal(C.grade(q,[0,1,99,-1,'2']),2/3);assert.equal(C.grade({...q,answer:[]},[0]),0);assert.equal(C.grade({...q,answer:[0,1,2,3]},[0,1,2,3]),1);});
test('Numeric syntax and tolerance boundaries',()=>{for(let a of ['12garbage','NaN','Infinity','1 2','12 W'])assert.equal(C.number(a),null);assert.equal(C.number('−2.5e-3'),-.0025);let q={type:'num',answer:2,tol:.1};assert.equal(C.grade(q,'2.1'),1);assert.equal(C.grade(q,'1.9'),1);assert.equal(C.grade(q,'2.10001'),0);});
test('Quiz and final drafts, cards, settings and project round trip',()=>{let p=C.blank();p.profile.name='<script>person</script>';p.profile.sid='A"&B';p.settings.instructor='<img>';p.settings.theme='dark';p.lessons.m01l1=true;p.project.topic='Pump';p.project.checks='ΔpQ checked';p.cards.m01t0={step:2,due:12345,reps:3};for(let key of ['m01','m05','m07','final']){let qs=C.questions(key,42);p.drafts[key]={seed:42,answers:{[qs[0].id]:qs[0].type==='num'?'1':qs[0].answer}};}let restored=C.normalize(clone(p));for(let field of ['profile','settings','lessons','project','cards'])assert.deepEqual(clone(restored[field]),clone(p[field]));for(let key of Object.keys(p.drafts)){assert.equal(restored.drafts[key].seed,42);for(let [id,a] of Object.entries(p.drafts[key].answers))assert.deepEqual(clone(restored.drafts[key].answers[id]),clone(a));}assert.deepEqual(clone(C.normalize(clone(restored))),clone(restored));});
test('Imported scores recomputed and bad fields normalized',()=>{let p=C.blank();p.attempts.m01=[{ts:'2026-10-06T00:00:00Z',seed:42,answers:{},score:999}];p.attempts.fake=[{score:100}];p.lessons.fake=true;p.profile.name='x'.repeat(1000);p.drafts.final={seed:'bad',answers:{}};p.cards.m01t0={step:99,due:Infinity,reps:-5};let r=C.normalize(clone(p));assert.equal(r.attempts.m01[0].score,0);assert(!r.attempts.fake);assert(!r.lessons.fake);assert.equal(r.profile.name.length,80);assert(!r.drafts.final);assert.equal(r.cards.m01t0.step,4);});
test('Best attempts, grade bands and all-assessment eligibility',()=>{let p=C.blank();for(let key of [...C.MODS.map(m=>m.id),'final']){let a={};C.questions(key,4).forEach(q=>a[q.id]=q.type==='num'?String(q.answer):q.answer);p.attempts[key]=[C.scoreAttempt(key,4,a),C.scoreAttempt(key,5,{})];}let g=C.grading(p);assert.equal(g.overall,100);assert(g.eligible);assert.equal(g.band,'Distinction');delete p.attempts.m01;assert(!C.grading(p).eligible);assert(!C.grading(C.blank()).eligible);});
test('Grade boundaries',()=>{for(let [score,band,eligible] of [[69.99,'Not yet completed',false],[70,'Pass',true],[80,'Merit',true],[90,'Distinction',true]]){let p=C.blank();for(let key of [...C.MODS.map(m=>m.id),'final'])p.attempts[key]=[{score}];assert.equal(C.grading(p).band,band);assert.equal(C.grading(p).eligible,eligible);}});
test('Storage write failure preserves in-memory progress',()=>{ctx.location={hash:'#/progress'};ctx.localStorage={setItem:()=>{throw Error('blocked')}};vm.runInContext("P=blank();P.profile.name='Saved in memory';storageOK=true;storageBanner=()=>{};navStats=()=>{};save();",ctx);assert.equal(vm.runInContext('storageOK',ctx),false);assert.equal(vm.runInContext('P.profile.name',ctx),'Saved in memory');assert.equal(vm.runInContext('P.view',ctx),'#/progress');});
test('Invalid course/schema rejected and invalid route constrained',()=>{assert.throws(()=>C.normalize({schema:'other'}));let p=C.blank();p.courseId='OTHER';assert.throws(()=>C.normalize(p));assert.equal(C.route('#/m/99/1').hash,'#/home');assert.equal(C.route('#/m/2/quiz').hash,'#/m/2/quiz');});
test('History truncation preserves old best and latest',()=>{let p=C.blank(),a={};C.questions('m01',1).forEach(q=>a[q.id]=q.answer);p.attempts.m01=[C.scoreAttempt('m01',1,a)];for(let i=0;i<250;i++)p.attempts.m01.push(C.scoreAttempt('m01',i,{}));let r=C.normalize(clone(p));assert.equal(r.attempts.m01.length,200);assert.equal(C.best(r,'m01'),100);assert.equal(r.attempts.m01.at(-1).seed,249);});
const html=fs.readFileSync('AI_101_for_Mechanical_Engineers.html','utf8');test('Embedded script compiles; no external script/style/network dependency',()=>{const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,1);new vm.Script(scripts[0][1]);assert(!/<script[^>]+src=|<link[^>]+rel=["']stylesheet/i.test(html));assert(!/fetch\(|XMLHttpRequest|window\.claude|https?:\/\/[^'"\s]+\.(?:js|css)/.test(scripts[0][1]));});
console.log(passed+' test groups passed');
